vendor: Itera Technologies
name: Taikun
version: v0.9.1
website_url: https://taikun.cloud
documentation_url: https://itera.gitbook.io/taikun
product_logo_url: https://taikun.cloud/assets/taikun-logo.svg
type: hosted platform
description: Taikun is a hybrid cloud management orchestration platform
