vendor: Whitestack
name: Whitemist
version: fornebu-3
website_url: https://www.whitestack.com/products/whitemist/
repo_url: 
documentation_url: https://docu.whitestack.com/whitemist/eclipse/manual_operaciones/introduction.html
product_logo_url: whitestack.svg 
type: distribution
description: 'WhiteMist is Whitestack's own Kubernetes distribution, geared at accelerating the adoption of containers in Cloud providers, E-commerce providers, Large organizations and Telecom Operators.'
