vendor: Chinaunicom Cloud
name: Chinaunicom Kubernetes Engine
version: v1.22.1
website_url: https://www.cucloud.cn/product/csk.html
documentation_url: https://www.cucloud.cn/product/csk.html
product_logo_url: https://www.cucloud.cn/upload/1/cms/category/1638524149286.png
type: hosted platform
description: Chinaunicom Kubernetes Engine (CKE), Fully compatible with Kubernetes' native API and capable of expanding Chinaunicom Cloud's Kubernetes plugins such as CNI and CSI, and a highly scalable and high-performance container management services.
