vendor: NHN
name: NHN Kubernetes Service NKS
version: v1.21.6
website_url: https://www.toast.com
documentation_url: https://docs.toast.com/en/Container/Kubernetes/en/overview/
product_logo_url: https://static.toastoven.net/toast/nks/logo_nks.svg
type: hosted platform
description: 'NKS(NHN Kubernetes Service) is a managed Kubernetes service that allows you to easily deploy a Kubernetes cluster in NHN Cloud.'
