vendor: Scaleway
name: Scaleway Kubernetes Kapsule
version: v1.23.0
website_url: http://www.scaleway.com/en/kubernetes/
documentation_url: https://developers.scaleway.com/en/products/k8s/api/
product_logo_url: https://www.scaleway.com/assets/images/logos/scaleway_logo_2018.svg
type: hosted
description: 'Kubernetes Kapsule provides a simple way to deploy and manage your containerized applications in the cloud. Relax and focus on your software stack while we take care of your clusters.'
