vendor: Nokia
name: Nokia Container Services (NCS)
version: NCS 22
website_url: https://www.nokia.com/networks/products/nokia-container-services/
documentation_url: https://www.nokia.com/networks/products/nokia-container-services/
type: distribution
description: 'Nokia Container Services is ready to use, pre-integrated, and based on open source toolsets and software services. Designed for Communication Service Providers (CSPs), it enables deploying and managing cloud-native applications, whether inside a Virtual Machine (VM) or Bare Metal (BM).'