vendor: Puppet
name: puppetlabs-kubernetes
version: v6.3.0
website_url: https://forge.puppet.com/puppetlabs/kubernetes
documentation_url: https://forge.puppet.com/puppetlabs/kubernetes/readme
product_logo_url: https://puppet.com/images/logos/puppet-logo-black.svg
type: installer
description: This Puppet module installs and configures Kubernetes allowing Kubernetes deployments to be managed using either
             Open Source Puppet or Puppet Enterprise. Puppet will maintain the state of your Kubernetes deployments automatically.
             Using this module will help you deploy Kubernetes quicker, using the Puppet DSL to define the state. It is fully open-source
             and community contributions are welcome.