vendor: Rancher Inc.
name: Rancher Kubernetes
version: v2.6.3-rc4
website_url: https://rancher.com/kubernetes/
documentation_url: https://rancher.com/docs/rancher/v2.x/en/
product_logo_url: https://rancher.com/img/brand-guidelines/assets/logos/png/color/rancher-logo-horiz-color.png
type: distribution
description: 'Deploy Rancher’s Kubernetes distro anywhere or launch cloud Kubernetes services from Google, Amazon or Microsoft.'
