vendor: IBM
name: IBM Cloud Kubernetes Service
version: 1.20.15
website_url: https://www.ibm.com/cloud/kubernetes-service
documentation_url: https://cloud.ibm.com/docs/containers
product_logo_url: https://github.com/ibm-cloud-docs/containers/blob/master/images-ui-only/logo-ibm-cloud-kubernetes-service-light.svg
type: hosted
description: 'IBM Cloud Kubernetes Service is a managed offering to create your own Kubernetes cluster of compute hosts to deploy and manage containerized apps on IBM Cloud.'
