vendor: Mail.Ru Cloud Solutions
name: Mail.Ru Cloud Containers
version: v1.21.4-mcs.1
website_url: https://mcs.mail.ru/en/ 
documentation_url: https://mcs.mail.ru/help/containers
product_logo_url: https://hb.bizmrg.com/mcs-static/___files/logo/mcs_logo_v1_black_text.svg
type: hosted
description: Mail.Ru Cloud Containers is a managed service for Kubernetes that makes it easy for you to run Kubernetes clusters on any OpenStack-compatible cloud. Mail.Ru Cloud Solutions provides hybrid cloud-based services that enable businesses to run their workload in a public or private cloud.
