vendor: acornsoft
name: Cocktail Cloud
version: v4.6
website_url: http://www.cocktailcloud.io/what-is-cocktail-cloud/
documentation_url: https://acornapps.github.io/cocktail-manual-3.4.1/docs/en/0.0/
product_logo_url: http://cocktailcloud.io/wp-content/uploads/2019/03/cocktailcloud_acornsoft.svg
type: distribution
description: 'A cocktail cloud is a container application management platform that provides a continuous development/deployment/operating environment for container-based applications.
