vendor: Xenonstack Inc
name: Nexastack Managed Kubernetes
version: v1.0.0
website_url: https://www.nexastack.com
documentation_url: https://www.nexastack.com
product_logo_url: https://drive.google.com/file/d/1lrczU4HFXJS2JqLc3TMnmF9H8UpRm-R-/view?usp=sharing
type: hosted platform
description: Nexastack is a  Platform for the Automation of Cloud Native and IaC Tools for Effective Infrastructure Management
