vendor: Microsoft
name: Azure Kubernetes Service AKS
version: v1.23.3
website_url: https://docs.microsoft.com/en-us/azure/aks/
documentation_url: https://docs.microsoft.com/en-us/azure/aks/
product_logo_url: https://raw.githubusercontent.com/cncf/landscape/master/cached_logos/azure-kubernetes-service-aks.svg
type: hosted platform
description: 'AKS allows you to quickly deploy a production ready Kubernetes cluster in Azure.'
