vendor: China-ASEAN Information Harbor
name: CAIH Container Cloud
version: 3.0.0
website_url: http://www.caih.com/index.html?lang=en_US
documentation_url: http://www.caih.com/subpage_302.html
product_logo_url: https://drive.google.com/file/d/0BzHEEzSiEt13RF9sWlVrUV8tOHNRNWQwV3BxQkxQOVBJVW1j/view?usp=sharing
type: distribution
description: CAIH Container Cloud provides enterprise-level Cloud Native, CICD and DevOps products, solutions and best practices to help enterprises modernize application architecture, maximize productivity, lower operational costs, and accelerate enterprise innovation.