vendor: Baidu Cloud
name: Baidu Cloud Container Engine
version: v1.22.5
website_url: https://cloud.baidu.com/product/cce.html
documentation_url: https://cloud.baidu.com/doc/CCE/index.html
product_logo_url: https://landscape.cncf.io/logos/baidu-kcsp.svg
type: hosted
description: 'Baidu Cloud Container Engine, aka CCE.'
