vendor: STACKIT - Schwarz IT KG
name: STACKIT Kubernetes Engine SKE
version: v1.21.0
website_url: https://stackit.de/en/
documentation_url: https://docs.stackit.cloud/display/public/STACKIT/Kubernetes
product_logo_url: https://cdn.apps.01.cf.eu01.stackit.cloud/assets/img/logo_inverted.svg
type: hosted platform
description: "STACKIT Kubernetes Engine (SKE) is a fully managed and scalable Kubernetes service for the deployment and management of Kubernetes clusters and containerized applications."
