vendor: Alibaba Cloud
name: Alibaba Cloud Container Service for Kubernetes
version: v1.22.3
website_url: https://www.aliyun.com/product/kubernetes
documentation_url: https://help.aliyun.com/document_detail/86737.html
product_logo_url: https://avatars2.githubusercontent.com/u/16377432?s=200&v=4
type: platform
description: Alibaba Cloud Container Service for Kubernetes (ACK) is a fully-managed service compatible with Kubernetes to help users focus on their applications rather than managing container infrastructure.
